### ISSUE TITLE
Sitemap generation problems

### ISSUE THREAD

**Issue by br1luca** [tradetracker-com/magento2#7]
**Describe the bug**
During the generation of a sitemap, we are getting error 500.

**What needs to be done to fix this issue**
Add this following code, is fixing the error.

Service\ProductData\AttributeCollector\Data\Category.php
```php
        foreach ($data as $entityId => $categoryPathes) {
            $usedPath = [];
            foreach ($categoryPathes as $categoryPath) {
                if ($categoryPath == null) {
                    continue;
                }
                $categoryIds = explode('/', $categoryPath);
                $key = array_search($rootCategoryId, $categoryIds);
````
This patch is fixing the error when $categoryPath is null.

Service\ProductData\Type.php
```php
            if (isset($data[$entityId]['parent_id']) && isset($data[$data[$entityId]['parent_id']])) {
                if (!isset($data[$data[$entityId]['parent_id']]['type_id'])) {
                    continue;
                }
                $typeId = $data[$data[$entityId]['parent_id']]['type_id'];
```
This patch is fixing the ['type_id'] not defined.

**Comment by Marvin-Magmodules** [comment]
Hi @br1luca,

Thank you for opening this issue with a detailed error trace! We are happy to share that we've just released the new [1.2.2](https://github.com/tradetracker-com/magento2/releases/tag/v1.2.2) version with a fix for this issue. 

We are closing this issue now but please feel free to reopen the issue if this still occurs.
